spring.application.name=${SPRING_APP_NAME:step_app_db}
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# Base de Datos - Variables de entorno para credenciales (SI SE LANZA EN LOCAL llegan desde .env en la carpeta backend)
# SI SE LANZA EN PRODUCCIÓN llegan desde el servidor cloud (Render, Vercel, etc)
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA / Hibernate
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Pool de Conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# JSON & Pageable
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.data.web.pageable.default-page-size=10
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Seguridad - Log Level y Secret Key
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:INFO}

# Clave secreta de JWT (ATENCION: Esta clave es predeterminada para probar el codigo en entorno local, sin necesidad
# de configuraciones, usar bajo responsabilidad propia). O puedes crear un archivo .env y meter tu clave codificada en
# Base64
application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# =========================================================
# Inicializacion nativa de Base de Datos
# =========================================================
# Permite que independientemente de Docker, si la base de datos se 
# auto-crea (XAMPP/WAMP), se cargue el fichero data.sql tras arrancar.
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true